"use client"

import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from "react"

type Language = "tr" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Header
    "header.tagline": "Güvenli duygusal destek alanın",
    "header.anonymous": "Anonim",
    "header.safe": "Güvenli",

    // Navigation
    "nav.home": "Ana Sayfa",
    "nav.forum": "Forum",
    "nav.aiChat": "AI Destekçi",
    "nav.about": "Hakkımızda",
    "nav.profile": "Profil",
    "nav.settings": "Ayarlar",
    "nav.logout": "Çıkış Yap",
    "nav.login": "Giriş Yap",
    "nav.register": "Kayıt Ol",

    // Welcome Section
    "welcome.title": "Comfortillo'ya Hoş Geldin",
    "welcome.subtitle": "Burada güvendesin. Duygularını paylaş, anlayışlı bir topluluktan destek al. Sen yalnız değilsin ve her zaman birisi seni dinlemeye hazır.",
    "welcome.badge.anonymous": "100% Anonim",
    "welcome.badge.safe": "Güvenli Topluluk",
    "welcome.badge.support": "7/24 Destek",
    "welcome.feature.forum.title": "Topluluk Forumu",
    "welcome.feature.forum.desc": "Duygularını paylaş, benzer deneyimler yaşayan insanlarla bağlantı kur. Herkes birbirini anlıyor ve destekliyor.",
    "welcome.feature.ai.title": "AI Destekçin",
    "welcome.feature.ai.desc": "7/24 anlayışlı AI destekçinle konuş. Yargılamadan dinler, empati kurar ve ihtiyacın olduğunda profesyonel yardım önerir.",
    "welcome.feature.privacy.title": "Tam Gizlilik",
    "welcome.feature.privacy.desc": "Kimliğin tamamen anonim kalır. Sadece sen ne kadar paylaşmak istiyorsan o kadar görünür. Gizliliğin bizim önceliğimiz.",
    "welcome.feature.professional.title": "Profesyonel Destek",
    "welcome.feature.professional.desc": "Acil durumlarda profesyonel yardım kaynaklarına yönlendirme. Kriz anlarında doğru yerlere ulaşman için rehberlik.",
    "welcome.cta.title": "Başlamaya Hazır mısın?",
    "welcome.cta.desc": "Duygusal destek almak ve vermek için topluluğumuza katıl. İlk adımı atmak bazen en zor olanıdır, ama sen yalnız değilsin.",
    "welcome.cta.members": "destekleyen üye",
    "welcome.cta.posts": "paylaşım",

    // AI Chat
    "aiChat.title": "AI Destekçin",
    "aiChat.subtitle": "7/24 anlayışlı ve güvenli destek",
    "aiChat.badge.active": "Aktif",
    "aiChat.badge.anonymous": "Anonim & Güvenli",
    "aiChat.badge.nonjudgmental": "Yargılamayan",
    "aiChat.chatTitle": "Sohbet",
    "aiChat.clearChat": "Sohbeti Temizle",
    "aiChat.placeholder": "Duygularını, düşüncelerini buraya yazabilirsin...",
    "aiChat.footer": "AI destekçin seni dinliyor ve anlıyor. Güvendesin.",
    "aiChat.welcome": "Merhaba! Ben Comfortillo'nun AI destekçisiyim. Burada güvendesin ve her ne hissediyorsan paylaşabilirsin. Seni dinliyorum ve anlıyorum. Nasıl hissediyorsun bugün?",
    "aiChat.error": "Üzgünüm, şu anda bir sorun yaşıyorum. Lütfen daha sonra tekrar deneyin. Acil bir durumsa, lütfen aşağıdaki acil yardım kaynaklarını kullan.",

    // Chat Suggestions
    "suggestions.title": "Nasıl başlayacağını bilmiyor musun? Bu önerilerden birini seçebilirsin:",
    "suggestions.1": "Kendimi çok yalnız hissediyorum",
    "suggestions.2": "Stresle nasıl başa çıkabilirim?",
    "suggestions.3": "Kaygılarım beni tüketiyor",
    "suggestions.4": "Ailemle sorunlarım var",
    "suggestions.5": "Motivasyonumu kaybettim",
    "suggestions.6": "Uyku sorunları yaşıyorum",

    // Emergency Resources
    "emergency.title": "Acil Durum Kaynakları",
    "emergency.warning": "Kendine zarar verme düşüncen varsa veya acil yardıma ihtiyacın varsa, lütfen hemen aşağıdaki kaynaklardan birine ulaş:",
    "emergency.reminder": "Hatırla: Profesyonel yardım almak güçlülük işaretidir. Sen değerlisin ve yardımı hak ediyorsun.",
    "emergency.suicide.name": "İntihar Önleme Hattı",
    "emergency.suicide.desc": "7/24 ücretsiz destek hattı",
    "emergency.health.name": "Sağlık Bakanlığı ALO 184",
    "emergency.health.desc": "Psikolojik destek hattı",
    "emergency.psychologists.name": "Türk Psikologlar Derneği",
    "emergency.psychologists.desc": "Profesyonel psikolojik destek",

    // Forum
    "forum.title": "Topluluk Forumu",
    "forum.subtitle": "Duygularını paylaş, başkalarının hikayelerini dinle. Burada herkes birbirini anlıyor ve destekliyor.",
    "forum.searchResults": "Arama Sonuçları",
    "forum.resultsFound": "sonuç bulundu",
    "forum.noResults": "Aradığınız kriterlere uygun sonuç bulunamadı",
    "forum.postsFound": "paylaşım bulundu",
    "forum.supporters": "Destekleyen",
    "forum.posts": "Paylaşım",
    "forum.support": "Destek",
    "forum.active": "Aktif",
    "forum.createPost": "Duygularını Paylaş",
    "forum.showLeaderboard": "Liderlik Tablosunu Göster",
    "forum.showForum": "Forumu Göster",
    "forum.emptyCategory": "Bu kategoride henüz paylaşım yok",
    "forum.emptySearch": "Arama sonucu bulunamadı",
    "forum.emptyAction": "İlk paylaşımı sen yap ve topluluğa öncülük et",
    "forum.emptySearchAction": "Farklı anahtar kelimeler deneyebilir veya yeni bir paylaşım yapabilirsin",
    "forum.all": "Tümü",

    // Categories
    "category.loneliness": "Yalnızlık",
    "category.stress": "Stres",
    "category.family": "Aile",
    "category.relationships": "İlişkiler",
    "category.anxiety": "Kaygı",
    "category.depression": "Depresyon",
    "category.other": "Diğer",

    // Post Card
    "post.support": "Destek",
    "post.reply": "Yanıt",
    "post.deleteConfirm": "Bu paylaşımı silmek istediğinizden emin misiniz?",
    "post.timeAgo.days": "gün önce",
    "post.timeAgo.hours": "saat önce",
    "post.timeAgo.now": "Az önce",

    // Replies
    "replies.title": "Yanıtlar",
    "replies.placeholder": "Bu kişiye nasıl yardım edebilirsin? Deneyimlerini, önerilerini paylaş...",
    "replies.replyPlaceholder": "Yanıta yanıt yazın...",
    "replies.loginRequired": "Yanıt yazmak için giriş yapmalısın...",
    "replies.loginLink": "giriş yapmalısın",
    "replies.replyTo": "Bir yanıta yanıt veriyorsunuz",
    "replies.cancel": "İptal",
    "replies.submit": "Yanıt Ver",
    "replies.replyBtn": "Yanıtla",
    "replies.sending": "Gönderiliyor...",
    "replies.characters": "karakter",
    "replies.solutionBadge": "Sorun Çözücü! (+5 Comforter)",
    "replies.markSolution": "Sorun Çözücü!",

    // Leaderboard
    "leaderboard.title": "Comforter Liderlik Tablosu",
    "leaderboard.subtitle": "En çok yardım eden topluluk üyeleri",
    "leaderboard.empty": "Henüz liderlik tablosunda kimse yok",
    "leaderboard.emptyAction": "İlk sen ol ve başkalarına yardım et!",

    // Search
    "search.placeholder": "Paylaşımlarda ara...",
    "search.button": "Ara",

    // About
    "about.title": "Comfortillo Hakkında",
    "about.tagline": "Güvenli duygusal destek alanın",
    "about.intro": "Comfortillo, Türkiye'deki bireylerin duygusal zorluklarını güvenle paylaşabilecekleri, anonim ve empatik bir dijital platform olarak tasarlandı. Burada yalnız değilsin.",
    "about.mission.title": "Misyonumuz",
    "about.mission.desc": "Mental sağlık desteğini herkes için erişilebilir kılmak. Stigmaları kırmak, empatiyi yaygınlaştırmak ve kimsenin duygusal zorluklarla yalnız kalmamasını sağlamak.",
    "about.why.title": "Neden Comfortillo?",
    "about.feature.anonymous.title": "Tamamen Anonim",
    "about.feature.anonymous.desc": "Kimliğin gizli kalır, sadece duyguların konuşur. Güvenli ve özel bir ortam.",
    "about.feature.community.title": "Anlayışlı Topluluk",
    "about.feature.community.desc": "Seni yargılamayan, destekleyen bir topluluk. Herkes birbirini anlıyor.",
    "about.feature.ai.title": "AI Destekçi",
    "about.feature.ai.desc": "7/24 anlayışlı AI destekçin her zaman yanında. Empati kurar ve dinler.",
    "about.feature.access.title": "7/24 Erişim",
    "about.feature.access.desc": "İstediğin zaman, istediğin yerden duygularını paylaşabilirsin.",
    "about.impact.title": "Etki Alanımız",
    "about.impact.supported": "Desteklenen Kişi",
    "about.impact.shared": "Paylaşılan Duygu",
    "about.impact.nonstop": "Kesintisiz Destek",
    "about.impact.safe": "Anonim & Güvenli",
    "about.howItWorks.title": "Nasıl Çalışır?",
    "about.step1.title": "1. Paylaş",
    "about.step1.desc": "Duygularını, düşüncelerini anonim olarak paylaş",
    "about.step2.title": "2. Bağlan",
    "about.step2.desc": "Topluluktan destek al, AI destekçinle konuş",
    "about.step3.title": "3. İyileş",
    "about.step3.desc": "Destekle, anlaşılarak duygusal iyileşme yolculuğuna başla",
    "about.security.title": "Güvenlik & Gizlilik",
    "about.security.data.title": "Veri Güvenliği",
    "about.security.data.desc": "Tüm veriler şifrelenir ve güvenli sunucularda saklanır. Kişisel bilgiler asla üçüncü taraflarla paylaşılmaz.",
    "about.security.anon.title": "Anonimlik",
    "about.security.anon.desc": "Kimlik bilgilerin gizli kalır. Sadece sen ne kadar paylaşmak istediğine karar verirsin.",
    "about.security.mod.title": "Moderasyon",
    "about.security.mod.desc": "Topluluk kurallarına uygun, güvenli bir ortam için sürekli moderasyon yapılır.",
    "about.security.emergency.title": "Acil Durum",
    "about.security.emergency.desc": "Kriz durumlarında otomatik olarak profesyonel yardım kaynakları önerilir.",
    "about.contact.title": "Bizimle İletişime Geç",
    "about.contact.desc": "Soruların, önerilerin veya geri bildirimlerin için bizimle iletişime geçebilirsin.",
    "about.contact.email": "E-posta",
    "about.contact.support": "Destek",
    "about.contact.supportAvailability": "7/24 AI destekçin her zaman yanında",

    // Settings
    "settings.title": "Ayarlar",
    "settings.account": "Hesap",
    "settings.appearance": "Görünüm",
    "settings.danger": "Tehlikeli Bölge",
    "settings.email": "E-posta Adresi",
    "settings.emailPlaceholder": "Yeni e-posta adresinizi girin",
    "settings.updateEmail": "E-posta Güncelle",
    "settings.password": "Şifre Değiştir",
    "settings.currentPassword": "Mevcut Şifre",
    "settings.newPassword": "Yeni Şifre",
    "settings.confirmPassword": "Yeni Şifre (Tekrar)",
    "settings.updatePassword": "Şifre Güncelle",
    "settings.darkMode": "Karanlık Mod",
    "settings.darkModeDesc": "Karanlık tema ile göz konforunu artırın",
    "settings.language": "Dil",
    "settings.languageDesc": "Arayüz dilini değiştirin",
    "settings.deleteAccount": "Hesabı Sil",
    "settings.deleteWarning": "Bu işlem geri alınamaz. Tüm verileriniz kalıcı olarak silinecektir.",
    "settings.deleteConfirmEmail": "Silmek için e-posta adresinizi girin:",
    "settings.save": "Kaydet",
    "settings.close": "Kapat",
    "settings.updating": "Güncelleniyor...",
    "settings.subtitle": "Profilini düzenle ve kişiselleştir",
    "settings.banner": "Profil Kapağı",
    "settings.bannerHint": "Önerilen boyut: 1200x300 piksel",
    "settings.photoHint": "Profil fotoğrafını değiştirmek için tıkla",
    "settings.name": "Ad Soyad",
    "settings.namePlaceholder": "Adınızı ve soyadınızı girin",
    "settings.nickname": "Kullanıcı Adı",
    "settings.nicknamePlaceholder": "Kullanıcı adınızı girin",
    "settings.age": "Yaş",
    "settings.agePlaceholder": "Yaşınızı girin",
    "settings.city": "Şehir",
    "settings.cityPlaceholder": "Şehrinizi girin",
    "settings.bio": "Biyografi",
    "settings.bioPlaceholder": "Kendin hakkında bir şeyler yaz...",
    "settings.interests": "İlgi Alanları",
    "settings.interestPlaceholder": "İlgi alanı ekle...",
    "settings.interestHint": "En fazla 10 ilgi alanı ekleyebilirsiniz",
    "settings.contentSettings": "İçerik Ayarları",
    "settings.nsfw": "NSFW İçerik",
    "settings.nsfwDescription": "Yetişkin içeriği görmek ve paylaşmak istiyorum",
    "settings.nsfwDisabledUnder18": "18 yaş altı kullanıcılar için bu özellik devre dışıdır",
    "settings.under18Warning": "18 yaşından küçük kullanıcılar bu özelliği kullanamaz",
    "settings.privacy": "Gizlilik",
    "settings.privacyText": "Profil bilgileriniz şifrelenerek saklanır. Kimliğiniz tamamen anonim kalır.",
    "settings.nsfwWarningTitle": "Yetişkin İçerik Uyarısı",
    "settings.warning": "Uyarı",
    "settings.nsfwWarningText": "Yetişkin içeriğini etkinleştirmek üzeresiniz. Bu içerikler hassas ve rahatsız edici olabilir.",
    "settings.nsfwPoint1": "Yetişkin içerikler 18+ olarak işaretlenir",
    "settings.nsfwPoint2": "Bu içerikler hassas temalar içerebilir",
    "settings.nsfwPoint3": "İçerikleri görüntülemek tamamen kendi sorumluluğunuzdadır",
    "settings.nsfwPoint4": "Topluluk kuralları yetişkin içerikler için de geçerlidir",
    "settings.responsibility": "Sorumluluk",
    "settings.responsibilityText": "Yetişkin içeriği görüntülemek ve paylaşmak tamamen kendi sorumluluğunuzdadır.",
    "settings.nsfwConfirm": "NSFW içeriğini etkinleştirmek istediğinizden emin misiniz?",
    "settings.enableYes": "Evet, Etkinleştir",
    "settings.cancel": "İptal",
    "settings.saving": "Kaydediliyor...",
    "settings.emailSettings": "E-posta Ayarları",
    "settings.emailAddress": "E-posta Adresi",
    "settings.emailUpdated": "E-posta başarıyla güncellendi!",
    "settings.emailUpdateError": "E-posta güncellenirken bir hata oluştu",
    "settings.changePassword": "Şifre Değiştir",
    "settings.changePasswordButton": "Şifreyi Güncelle",
    "settings.changing": "Değiştiriliyor...",
    "settings.fillAllFields": "Lütfen tüm alanları doldurun",
    "settings.passwordMismatch": "Yeni şifreler eşleşmiyor!",
    "settings.passwordMinLength": "Şifre en az 6 karakter olmalıdır",
    "settings.passwordChanged": "Şifreniz başarıyla değiştirildi!",
    "settings.passwordChangeError": "Şifre değiştirilirken bir hata oluştu",
    "settings.emailMismatch": "E-posta adresi eşleşmiyor!",
    "settings.accountDeleted": "Hesabınız başarıyla silindi.",
    "settings.accountDeleteError": "Hesap silinirken bir hata oluştu",
    "settings.appearanceSettings": "Görünüm Ayarları",
    "settings.darkModeActive": "Karanlık tema aktif — göz konforunu artırır",
    "settings.lightModeActive": "Aydınlık tema aktif — sıcak ve lüks bir görünüm",
    "settings.note": "Not",
    "settings.darkModeNote": "Tema değişikliğiniz otomatik olarak kaydedilir ve bir sonraki ziyaretinizde hatırlanır.",
    "settings.dangerZone": "Tehlikeli Bölge",
    "settings.deleteAccountWarning": "Hesabınızı silmek geri alınamaz bir işlemdir. Tüm paylaşımlarınız, yanıtlarınız ve profil bilgileriniz kalıcı olarak silinecektir.",
    "settings.deleteButton": "Hesabımı Sil",
    "settings.finalWarning": "Bu işlem geri alınamaz! Hesabınız ve tüm verileriniz kalıcı olarak silinecektir.",
    "settings.confirmEmail": "Onaylamak için e-posta adresinizi girin:",
    "settings.enterEmail": "E-posta adresinizi girin",
    "settings.deleting": "Siliniyor...",
    "settings.permanentlyDelete": "Kalıcı Olarak Sil",

    // Auth
    "auth.login": "Giriş Yap",
    "auth.register": "Kayıt Ol",
    "auth.email": "E-posta",
    "auth.password": "Şifre",
    "auth.name": "Ad Soyad",
    "auth.confirmPassword": "Şifre Tekrar",
    "auth.loginButton": "Giriş Yap",
    "auth.registerButton": "Kayıt Ol",
    "auth.logging": "Giriş yapılıyor...",
    "auth.registering": "Kayıt olunuyor...",
    "auth.acceptTerms": "Kayıt olarak aşağıdaki kuralları kabul etmiş olursunuz:",
    "auth.communityRules": "Topluluk Kuralları",
    "auth.privacyPolicy": "Gizlilik Politikası",
    "auth.termsOfService": "Kullanım Koşulları",
    "auth.welcomeTitle": "Comfortillo'ya Hoş Geldin",
    "auth.welcomeSubtitle": "Güvenli duygusal destek alanına katıl",
    "auth.passwordMismatch": "Şifreler eşleşmiyor!",
    "auth.acceptAllTerms": "Kayıt olmak için tüm şartları ve politikaları kabul etmelisiniz!",
    "auth.emailPlaceholder": "ornek@email.com",
    "auth.passwordPlaceholder": "Şifrenizi girin",
    "auth.forgotPassword": "Şifremi unuttum",
    "auth.namePlaceholder": "Adınız ve soyadınız",
    "auth.newPasswordPlaceholder": "Güçlü bir şifre oluşturun",
    "auth.confirmPasswordPlaceholder": "Şifrenizi tekrar girin",
    "auth.readAndAccept": "'nı okudum ve kabul ediyorum",
    "auth.reminder": "Hatırla: Comfortillo'da güvendesin. Verilerini koruyoruz ve kimliğin anonim kalır.",
    "auth.communityRulesTitle": "Topluluk Kuralları",
    "auth.privacyPolicyTitle": "Gizlilik Politikası",
    "auth.termsOfServiceTitle": "Kullanım Şartları",
    "auth.understood": "Anladım",

    // Profile
    "profile.editProfile": "Profili Düzenle",
    "profile.posts": "Paylaşımlar",
    "profile.replies": "Yanıtlar",
    "profile.solutions": "Çözümler",
    "profile.likes": "Beğeniler",
    "profile.joinedDate": "Katılma Tarihi",
    "profile.activity": "Aktiviteler",
    "profile.myPosts": "Paylaşımlarım",
    "profile.myReplies": "Yanıtlarım",
    "profile.interests": "İlgi Alanları",
    "profile.noInterests": "Henüz ilgi alanı eklenmedi",
    "profile.noPosts": "Henüz paylaşım yok",
    "profile.noPostsHint": "İlk paylaşımını yap ve topluluğa katıl!",
    "profile.noReplies": "Henüz yanıt yok",
    "profile.noRepliesHint": "Başkalarına destek olarak ilk yanıtını yaz!",
    "profile.report": "Bildir",
    "profile.support": "Destek",
    "profile.reply": "Yanıt",
    "profile.solutionBadge": "Sorun Çözücü",
    "profile.likeCount": "beğeni",
    "profile.loading": "Profil yükleniyor...",
    "profile.reportPostTitle": "profili bildirildi",
    "profile.defaultCity": "İstanbul",
    "profile.defaultBio": "Henüz bir bio eklenmedi.",

    // Create Post
    "createPost.title": "Duygularını Paylaş",
    "createPost.titleLabel": "Başlık",
    "createPost.titlePlaceholder": "Başlık yazın...",
    "createPost.category": "Kategori",
    "createPost.selectCategory": "Kategori seçin",
    "createPost.content": "İçerik",
    "createPost.contentPlaceholder": "Düşüncelerini, hislerini paylaş...",
    "createPost.media": "Medya (Opsiyonel)",
    "createPost.nsfwToggle": "NSFW İçerik",
    "createPost.submit": "Paylaş",
    "createPost.submitting": "Paylaşılıyor...",
    "createPost.cancel": "İptal",
    "createPost.anonymousNote": "Paylaşımın tamamen anonim olarak gönderilecektir. Topluluk kurallarına uygun içerik paylaşmayı unutma.",
    "createPost.titleNotAllowed": "Başlık uygun değil",
    "createPost.contentNotAllowed": "İçerik uygun değil",
    "createPost.nsfwRequirement": "Bu özelliği kullanmak için 18+ yaşında olmalı ve profil ayarlarından etkinleştirmelisiniz",
    "createPost.nsfwQuestion": "Bu paylaşım yetişkin içeriği içeriyor mu?",
    "createPost.nsfwUnder18": "18 yaşından küçük kullanıcılar NSFW içerik paylaşamaz",
    "createPost.nsfwEnable": "NSFW özelliğini profil ayarlarından etkinleştirin",
    "createPost.nsfwMarked": "Bu paylaşım yetişkin içeriği olarak işaretlenecek ve 18 yaş altı kullanıcılardan gizlenecek",
    "createPost.mediaHint": "Fotoğraf veya dosya eklemek istersen",
    "createPost.selectFile": "Dosya Seç",
    "createPost.reminder": "Hatırla: Paylaştığın her şey anonim kalacak. Burada güvendesin ve topluluk seni desteklemek için burada. Sen yalnız değilsin.",

    // Report
    "report.title": "İçeriği Bildir",
    "report.type": "Bildirim Türü",
    "report.description": "Açıklama",
    "report.descPlaceholder": "Bildirimin nedenini açıklayın...",
    "report.submit": "Bildir",
    "report.submitting": "Bildiriliyor...",
    "report.cancel": "İptal",
    "report.info": "Bildirimler moderasyon ekibimiz tarafından incelenir. Bildirimin anonim olarak gönderilecektir.",
    "report.falseWarning": "Yanlış veya kötü niyetli bildirimler hesabınızın askıya alınmasına neden olabilir.",
    "report.subtitle": "Topluluk kurallarına aykırı içerikleri bildirin",
    "report.reportedPost": "Bildirilen İçerik",
    "report.submitSuccess": "Bildirimin başarıyla gönderildi. Moderasyon ekibimiz inceleyecektir.",
    "report.submitError": "Bildirim gönderilirken bir hata oluştu. Lütfen tekrar deneyin.",
    "report.infoPoint1": "Bildiriminiz tamamen anonim olarak gönderilecektir",
    "report.infoPoint3": "Bildirimlerin sonuçları gizlilik politikamız gereği paylaşılmaz",
    "report.infoPoint4": "Acil durumlar için lütfen 155 veya 112'yi arayın",
    "report.type.harassment": "Taciz ve Zorbalık",
    "report.type.harassmentDesc": "Kişisel saldırı, tehdit veya taciz içeriği",
    "report.type.illegal": "Yasa Dışı Maddeler",
    "report.type.illegalDesc": "Uyuşturucu, silah veya yasa dışı aktiviteler",
    "report.type.spam": "Spam ve Reklam",
    "report.type.spamDesc": "İstenmeyen reklam veya spam içerik",
    "report.type.inappropriate": "Uygunsuz İçerik",
    "report.type.inappropriateDesc": "Topluluk kurallarına aykırı içerik",
    "report.type.misinformation": "Yanlış Bilgi",
    "report.type.misinformationDesc": "Zararlı veya yanıltıcı bilgi paylaşımı",
    "report.type.violence": "Şiddet",
    "report.type.violenceDesc": "Şiddet içeren veya teşvik eden içerik",
    "report.type.hate": "Nefret Söylemi",
    "report.type.hateDesc": "Ayrımcılık veya nefret içeren ifadeler",
    "report.type.other": "Diğer",
    "report.type.otherDesc": "Yukarıdakilerden farklı bir sorun",

    // Comforter Progress
    "comforter.progress": "Comforter İlerlemesi",
    "comforter.maxLevel": "Maksimum seviyeye ulaştın!",
    "comforter.pointsNeeded": "puan daha",
    "comforter.toReach": "olmak için",

    // Media Preview
    "media.sharedMedia": "Paylaşılan medya",
    "media.image": "Resim",
    "media.nsfwContent": "Yetişkin İçeriği",
    "media.clickToView": "Görüntülemek için tıklayın",
    "media.audioFile": "Ses Dosyası",
    "media.file": "Dosya",
    "media.imageNotFound": "Resim bulunamadı",
    "media.nsfwWarning": "Yetişkin İçeriği Uyarısı",
    "media.nsfwConfirm": "Bu içerik yetişkin materyali içermektedir. Görüntülemek istediğinizden emin misiniz?",
    "media.nsfwDisclaimer": "Bu içeriği görüntülemek tamamen kendi sorumluluğunuzdadır.",
    "media.yesView": "Evet, Görüntüle",

    // Common
    "common.loading": "Yükleniyor...",
    "common.error": "Bir hata oluştu",
    "common.success": "Başarılı",
    "common.cancel": "İptal",
    "common.save": "Kaydet",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.close": "Kapat",
  },
  en: {
    // Header
    "header.tagline": "Your safe emotional support space",
    "header.anonymous": "Anonymous",
    "header.safe": "Safe",

    // Navigation
    "nav.home": "Home",
    "nav.forum": "Forum",
    "nav.aiChat": "AI Companion",
    "nav.about": "About",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.logout": "Log Out",
    "nav.login": "Log In",
    "nav.register": "Sign Up",

    // Welcome Section
    "welcome.title": "Welcome to Comfortillo",
    "welcome.subtitle": "You are safe here. Share your feelings, get support from an understanding community. You are not alone and someone is always ready to listen.",
    "welcome.badge.anonymous": "100% Anonymous",
    "welcome.badge.safe": "Safe Community",
    "welcome.badge.support": "24/7 Support",
    "welcome.feature.forum.title": "Community Forum",
    "welcome.feature.forum.desc": "Share your feelings, connect with people who have similar experiences. Everyone understands and supports each other.",
    "welcome.feature.ai.title": "Your AI Companion",
    "welcome.feature.ai.desc": "Talk to your 24/7 understanding AI companion. It listens without judgment, empathizes, and suggests professional help when needed.",
    "welcome.feature.privacy.title": "Full Privacy",
    "welcome.feature.privacy.desc": "Your identity remains completely anonymous. Only you decide how much to share. Your privacy is our priority.",
    "welcome.feature.professional.title": "Professional Support",
    "welcome.feature.professional.desc": "Referral to professional help resources in emergencies. Guidance to reach the right places in crisis moments.",
    "welcome.cta.title": "Ready to Start?",
    "welcome.cta.desc": "Join our community to receive and give emotional support. Taking the first step is sometimes the hardest, but you are not alone.",
    "welcome.cta.members": "supporting members",
    "welcome.cta.posts": "posts shared",

    // AI Chat
    "aiChat.title": "Your AI Companion",
    "aiChat.subtitle": "24/7 understanding and safe support",
    "aiChat.badge.active": "Active",
    "aiChat.badge.anonymous": "Anonymous & Safe",
    "aiChat.badge.nonjudgmental": "Non-judgmental",
    "aiChat.chatTitle": "Chat",
    "aiChat.clearChat": "Clear Chat",
    "aiChat.placeholder": "Share your feelings and thoughts here...",
    "aiChat.footer": "Your AI companion is listening and understanding you. You are safe.",
    "aiChat.welcome": "Hello! I'm Comfortillo's AI companion. You are safe here and you can share whatever you feel. I'm listening and I understand. How are you feeling today?",
    "aiChat.error": "Sorry, I'm experiencing an issue right now. Please try again later. If it's an emergency, please use the emergency resources below.",

    // Chat Suggestions
    "suggestions.title": "Not sure how to start? Choose one of these suggestions:",
    "suggestions.1": "I feel very lonely",
    "suggestions.2": "How can I deal with stress?",
    "suggestions.3": "My anxieties are consuming me",
    "suggestions.4": "I have problems with my family",
    "suggestions.5": "I've lost my motivation",
    "suggestions.6": "I'm having sleep problems",

    // Emergency Resources
    "emergency.title": "Emergency Resources",
    "emergency.warning": "If you're having thoughts of self-harm or need urgent help, please reach out to one of these resources immediately:",
    "emergency.reminder": "Remember: Seeking professional help is a sign of strength. You are valuable and deserve help.",
    "emergency.suicide.name": "Suicide Prevention Line",
    "emergency.suicide.desc": "24/7 free support line",
    "emergency.health.name": "Ministry of Health ALO 184",
    "emergency.health.desc": "Psychological support line",
    "emergency.psychologists.name": "Turkish Psychologists Association",
    "emergency.psychologists.desc": "Professional psychological support",

    // Forum
    "forum.title": "Community Forum",
    "forum.subtitle": "Share your feelings, listen to others' stories. Here everyone understands and supports each other.",
    "forum.searchResults": "Search Results",
    "forum.resultsFound": "results found",
    "forum.noResults": "No results found matching your criteria",
    "forum.postsFound": "posts found",
    "forum.supporters": "Supporters",
    "forum.posts": "Posts",
    "forum.support": "Support",
    "forum.active": "Active",
    "forum.createPost": "Share Your Feelings",
    "forum.showLeaderboard": "Show Leaderboard",
    "forum.showForum": "Show Forum",
    "forum.emptyCategory": "No posts in this category yet",
    "forum.emptySearch": "No search results found",
    "forum.emptyAction": "Be the first to share and lead the community",
    "forum.emptySearchAction": "Try different keywords or create a new post",
    "forum.all": "All",

    // Categories
    "category.loneliness": "Loneliness",
    "category.stress": "Stress",
    "category.family": "Family",
    "category.relationships": "Relationships",
    "category.anxiety": "Anxiety",
    "category.depression": "Depression",
    "category.other": "Other",

    // Post Card
    "post.support": "Support",
    "post.reply": "Reply",
    "post.deleteConfirm": "Are you sure you want to delete this post?",
    "post.timeAgo.days": "days ago",
    "post.timeAgo.hours": "hours ago",
    "post.timeAgo.now": "Just now",

    // Replies
    "replies.title": "Replies",
    "replies.placeholder": "How can you help this person? Share your experiences and suggestions...",
    "replies.replyPlaceholder": "Write a reply to this comment...",
    "replies.loginRequired": "You must log in to write a reply...",
    "replies.loginLink": "log in",
    "replies.replyTo": "You are replying to a comment",
    "replies.cancel": "Cancel",
    "replies.submit": "Reply",
    "replies.replyBtn": "Reply",
    "replies.sending": "Sending...",
    "replies.characters": "characters",
    "replies.solutionBadge": "Problem Solver! (+5 Comforter)",
    "replies.markSolution": "Problem Solver!",

    // Leaderboard
    "leaderboard.title": "Comforter Leaderboard",
    "leaderboard.subtitle": "Community members who help the most",
    "leaderboard.empty": "No one on the leaderboard yet",
    "leaderboard.emptyAction": "Be the first and help others!",

    // Search
    "search.placeholder": "Search posts...",
    "search.button": "Search",

    // About
    "about.title": "About Comfortillo",
    "about.tagline": "Your safe emotional support space",
    "about.intro": "Comfortillo is designed as an anonymous and empathetic digital platform where individuals in Turkey can safely share their emotional challenges. You are not alone here.",
    "about.mission.title": "Our Mission",
    "about.mission.desc": "Making mental health support accessible to everyone. Breaking stigmas, spreading empathy, and ensuring no one faces emotional challenges alone.",
    "about.why.title": "Why Comfortillo?",
    "about.feature.anonymous.title": "Completely Anonymous",
    "about.feature.anonymous.desc": "Your identity stays hidden, only your feelings speak. A safe and private environment.",
    "about.feature.community.title": "Understanding Community",
    "about.feature.community.desc": "A community that doesn't judge you, supports you. Everyone understands each other.",
    "about.feature.ai.title": "AI Companion",
    "about.feature.ai.desc": "Your 24/7 understanding AI companion is always by your side. It empathizes and listens.",
    "about.feature.access.title": "24/7 Access",
    "about.feature.access.desc": "Share your feelings anytime, anywhere you want.",
    "about.impact.title": "Our Impact",
    "about.impact.supported": "People Supported",
    "about.impact.shared": "Emotions Shared",
    "about.impact.nonstop": "Non-stop Support",
    "about.impact.safe": "Anonymous & Safe",
    "about.howItWorks.title": "How It Works?",
    "about.step1.title": "1. Share",
    "about.step1.desc": "Share your feelings and thoughts anonymously",
    "about.step2.title": "2. Connect",
    "about.step2.desc": "Get support from the community, talk to your AI companion",
    "about.step3.title": "3. Heal",
    "about.step3.desc": "Start your emotional healing journey with support and understanding",
    "about.security.title": "Security & Privacy",
    "about.security.data.title": "Data Security",
    "about.security.data.desc": "All data is encrypted and stored on secure servers. Personal information is never shared with third parties.",
    "about.security.anon.title": "Anonymity",
    "about.security.anon.desc": "Your identity information stays private. Only you decide how much to share.",
    "about.security.mod.title": "Moderation",
    "about.security.mod.desc": "Continuous moderation for a safe environment in compliance with community rules.",
    "about.security.emergency.title": "Emergency",
    "about.security.emergency.desc": "Professional help resources are automatically suggested in crisis situations.",
    "about.contact.title": "Contact Us",
    "about.contact.desc": "Feel free to reach out for your questions, suggestions, or feedback.",
    "about.contact.email": "Email",
    "about.contact.support": "Support",
    "about.contact.supportAvailability": "Your 24/7 AI companion is always by your side",

    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.appearance": "Appearance",
    "settings.danger": "Danger Zone",
    "settings.email": "Email Address",
    "settings.emailPlaceholder": "Enter your new email address",
    "settings.updateEmail": "Update Email",
    "settings.password": "Change Password",
    "settings.currentPassword": "Current Password",
    "settings.newPassword": "New Password",
    "settings.confirmPassword": "Confirm New Password",
    "settings.updatePassword": "Update Password",
    "settings.darkMode": "Dark Mode",
    "settings.darkModeDesc": "Improve eye comfort with dark theme",
    "settings.language": "Language",
    "settings.languageDesc": "Change the interface language",
    "settings.deleteAccount": "Delete Account",
    "settings.deleteWarning": "This action cannot be undone. All your data will be permanently deleted.",
    "settings.deleteConfirmEmail": "Enter your email to confirm deletion:",
    "settings.save": "Save",
    "settings.close": "Close",
    "settings.updating": "Updating...",
    "settings.subtitle": "Edit and personalize your profile",
    "settings.banner": "Profile Banner",
    "settings.bannerHint": "Recommended size: 1200x300 pixels",
    "settings.photoHint": "Click to change your profile photo",
    "settings.name": "Full Name",
    "settings.namePlaceholder": "Enter your full name",
    "settings.nickname": "Username",
    "settings.nicknamePlaceholder": "Enter your username",
    "settings.age": "Age",
    "settings.agePlaceholder": "Enter your age",
    "settings.city": "City",
    "settings.cityPlaceholder": "Enter your city",
    "settings.bio": "Bio",
    "settings.bioPlaceholder": "Write something about yourself...",
    "settings.interests": "Interests",
    "settings.interestPlaceholder": "Add an interest...",
    "settings.interestHint": "You can add up to 10 interests",
    "settings.contentSettings": "Content Settings",
    "settings.nsfw": "NSFW Content",
    "settings.nsfwDescription": "I want to see and share adult content",
    "settings.nsfwDisabledUnder18": "This feature is disabled for users under 18",
    "settings.under18Warning": "Users under 18 cannot use this feature",
    "settings.privacy": "Privacy",
    "settings.privacyText": "Your profile information is encrypted and stored securely. Your identity remains completely anonymous.",
    "settings.nsfwWarningTitle": "Adult Content Warning",
    "settings.warning": "Warning",
    "settings.nsfwWarningText": "You are about to enable adult content. This content may be sensitive and disturbing.",
    "settings.nsfwPoint1": "Adult content is marked as 18+",
    "settings.nsfwPoint2": "This content may contain sensitive themes",
    "settings.nsfwPoint3": "Viewing content is entirely your own responsibility",
    "settings.nsfwPoint4": "Community rules also apply to adult content",
    "settings.responsibility": "Responsibility",
    "settings.responsibilityText": "Viewing and sharing adult content is entirely your own responsibility.",
    "settings.nsfwConfirm": "Are you sure you want to enable NSFW content?",
    "settings.enableYes": "Yes, Enable",
    "settings.cancel": "Cancel",
    "settings.saving": "Saving...",
    "settings.emailSettings": "Email Settings",
    "settings.emailAddress": "Email Address",
    "settings.emailUpdated": "Email updated successfully!",
    "settings.emailUpdateError": "An error occurred while updating email",
    "settings.changePassword": "Change Password",
    "settings.changePasswordButton": "Update Password",
    "settings.changing": "Changing...",
    "settings.fillAllFields": "Please fill in all fields",
    "settings.passwordMismatch": "New passwords don't match!",
    "settings.passwordMinLength": "Password must be at least 6 characters",
    "settings.passwordChanged": "Your password has been changed successfully!",
    "settings.passwordChangeError": "An error occurred while changing password",
    "settings.emailMismatch": "Email address doesn't match!",
    "settings.accountDeleted": "Your account has been successfully deleted.",
    "settings.accountDeleteError": "An error occurred while deleting account",
    "settings.appearanceSettings": "Appearance Settings",
    "settings.darkModeActive": "Dark theme active — improves eye comfort",
    "settings.lightModeActive": "Light theme active — warm and luxurious look",
    "settings.note": "Note",
    "settings.darkModeNote": "Your theme change is automatically saved and remembered on your next visit.",
    "settings.dangerZone": "Danger Zone",
    "settings.deleteAccountWarning": "Deleting your account is irreversible. All your posts, replies, and profile information will be permanently deleted.",
    "settings.deleteButton": "Delete My Account",
    "settings.finalWarning": "This action cannot be undone! Your account and all data will be permanently deleted.",
    "settings.confirmEmail": "Enter your email to confirm:",
    "settings.enterEmail": "Enter your email address",
    "settings.deleting": "Deleting...",
    "settings.permanentlyDelete": "Permanently Delete",

    // Auth
    "auth.login": "Log In",
    "auth.register": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Full Name",
    "auth.confirmPassword": "Confirm Password",
    "auth.loginButton": "Log In",
    "auth.registerButton": "Sign Up",
    "auth.logging": "Logging in...",
    "auth.registering": "Signing up...",
    "auth.acceptTerms": "By signing up, you accept the following rules:",
    "auth.communityRules": "Community Rules",
    "auth.privacyPolicy": "Privacy Policy",
    "auth.termsOfService": "Terms of Service",
    "auth.welcomeTitle": "Welcome to Comfortillo",
    "auth.welcomeSubtitle": "Join the safe emotional support space",
    "auth.passwordMismatch": "Passwords don't match!",
    "auth.acceptAllTerms": "You must accept all terms and policies to sign up!",
    "auth.emailPlaceholder": "example@email.com",
    "auth.passwordPlaceholder": "Enter your password",
    "auth.forgotPassword": "Forgot password",
    "auth.namePlaceholder": "Your full name",
    "auth.newPasswordPlaceholder": "Create a strong password",
    "auth.confirmPasswordPlaceholder": "Re-enter your password",
    "auth.readAndAccept": " — I have read and accept",
    "auth.reminder": "Remember: You are safe at Comfortillo. We protect your data and your identity stays anonymous.",
    "auth.communityRulesTitle": "Community Rules",
    "auth.privacyPolicyTitle": "Privacy Policy",
    "auth.termsOfServiceTitle": "Terms of Service",
    "auth.understood": "Got it",

    // Profile
    "profile.editProfile": "Edit Profile",
    "profile.posts": "Posts",
    "profile.replies": "Replies",
    "profile.solutions": "Solutions",
    "profile.likes": "Likes",
    "profile.joinedDate": "Joined",
    "profile.activity": "Activity",
    "profile.myPosts": "My Posts",
    "profile.myReplies": "My Replies",
    "profile.interests": "Interests",
    "profile.noInterests": "No interests added yet",
    "profile.noPosts": "No posts yet",
    "profile.noPostsHint": "Make your first post and join the community!",
    "profile.noReplies": "No replies yet",
    "profile.noRepliesHint": "Write your first reply and support others!",
    "profile.report": "Report",
    "profile.support": "Support",
    "profile.reply": "Reply",
    "profile.solutionBadge": "Problem Solver",
    "profile.likeCount": "likes",
    "profile.loading": "Loading profile...",
    "profile.reportPostTitle": "profile reported",
    "profile.defaultCity": "Istanbul",
    "profile.defaultBio": "No bio added yet.",

    // Create Post
    "createPost.title": "Share Your Feelings",
    "createPost.titleLabel": "Title",
    "createPost.titlePlaceholder": "Write a title...",
    "createPost.category": "Category",
    "createPost.selectCategory": "Select a category",
    "createPost.content": "Content",
    "createPost.contentPlaceholder": "Share your thoughts and feelings...",
    "createPost.media": "Media (Optional)",
    "createPost.nsfwToggle": "NSFW Content",
    "createPost.submit": "Share",
    "createPost.submitting": "Sharing...",
    "createPost.cancel": "Cancel",
    "createPost.anonymousNote": "Your post will be shared completely anonymously. Remember to share content that complies with community rules.",
    "createPost.titleNotAllowed": "Title is not appropriate",
    "createPost.contentNotAllowed": "Content is not appropriate",
    "createPost.nsfwRequirement": "You must be 18+ and enable this feature from your profile settings",
    "createPost.nsfwQuestion": "Does this post contain adult content?",
    "createPost.nsfwUnder18": "Users under 18 cannot share NSFW content",
    "createPost.nsfwEnable": "Enable NSFW from your profile settings",
    "createPost.nsfwMarked": "This post will be marked as adult content and hidden from users under 18",
    "createPost.mediaHint": "If you want to add a photo or file",
    "createPost.selectFile": "Choose File",
    "createPost.reminder": "Remember: Everything you share stays anonymous. You are safe here and the community is here to support you. You are not alone.",

    // Report
    "report.title": "Report Content",
    "report.type": "Report Type",
    "report.description": "Description",
    "report.descPlaceholder": "Explain the reason for your report...",
    "report.submit": "Report",
    "report.submitting": "Reporting...",
    "report.cancel": "Cancel",
    "report.info": "Reports are reviewed by our moderation team. Your report will be sent anonymously.",
    "report.falseWarning": "False or malicious reports may result in your account being suspended.",
    "report.subtitle": "Report content that violates community rules",
    "report.reportedPost": "Reported Content",
    "report.submitSuccess": "Your report has been successfully submitted. Our moderation team will review it.",
    "report.submitError": "An error occurred while submitting the report. Please try again.",
    "report.infoPoint1": "Your report will be sent completely anonymously",
    "report.infoPoint3": "Report outcomes are not shared due to our privacy policy",
    "report.infoPoint4": "For emergencies, please call 155 or 112",
    "report.type.harassment": "Harassment & Bullying",
    "report.type.harassmentDesc": "Personal attacks, threats, or harassment",
    "report.type.illegal": "Illegal Substances",
    "report.type.illegalDesc": "Drugs, weapons, or illegal activities",
    "report.type.spam": "Spam & Advertising",
    "report.type.spamDesc": "Unsolicited advertising or spam content",
    "report.type.inappropriate": "Inappropriate Content",
    "report.type.inappropriateDesc": "Content violating community rules",
    "report.type.misinformation": "Misinformation",
    "report.type.misinformationDesc": "Harmful or misleading information",
    "report.type.violence": "Violence",
    "report.type.violenceDesc": "Content containing or promoting violence",
    "report.type.hate": "Hate Speech",
    "report.type.hateDesc": "Discriminatory or hateful expressions",
    "report.type.other": "Other",
    "report.type.otherDesc": "A different issue not listed above",

    // Comforter Progress
    "comforter.progress": "Comforter Progress",
    "comforter.maxLevel": "Maximum level reached!",
    "comforter.pointsNeeded": "more points",
    "comforter.toReach": "to become",

    // Media Preview
    "media.sharedMedia": "Shared media",
    "media.image": "Image",
    "media.nsfwContent": "Adult Content",
    "media.clickToView": "Click to view",
    "media.audioFile": "Audio File",
    "media.file": "File",
    "media.imageNotFound": "Image not found",
    "media.nsfwWarning": "Adult Content Warning",
    "media.nsfwConfirm": "This content contains adult material. Are you sure you want to view it?",
    "media.nsfwDisclaimer": "Viewing this content is entirely your own responsibility.",
    "media.yesView": "Yes, View",

    // Common
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.close": "Close",
  },
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("tr")

  useEffect(() => {
    const saved = localStorage.getItem("comfortillo-language")
    if (saved === "en" || saved === "tr") {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("comfortillo-language", lang)
  }, [])

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key
    },
    [language]
  )

  const value = useMemo(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t]
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
